storage: ./storage
store:
  aws-s3-storage:
    bucket: AWS_BUCKET_NAME
    #keyPrefix: AWS_KEYPREFIX_NAME # optional, has the effect of nesting all files in a subdirectory
    region: AWS_REAGION # optional, will use aws s3's default behavior if not specified
    #endpoint: https://{service}.{region}.amazonaws.com # optional, will use aws s3's default behavior if not specified
    #s3ForcePathStyle: false # optional, will use path style URLs for S3 objects
    accessKeyId: AWS_ACCESSKEY_ID # optional, aws accessKeyId for private S3 bucket
    secretAccessKey: AWS_SECRETKEY # optional, aws secretAccessKey for private S3 bucket
auth:
  github-oauth-ui:
    org: GITHUB_OAUTH_ORG
uplinks:
  npmjs:
    url: https://registry.npmjs.org/
packages:
  '@*/*':
    access: $authenticated
    publish: $authenticated
    proxy: npmjs
  '**':
    proxy: npmjs
    access: $authenticated
    publish: $authenticated
logs:
  - {type: stdout, format: pretty, level: http}
middlewares:
  github-oauth-ui:
    client-id: GITHUB_OAUTH_CLIENT_ID
    client-secret: GITHUB_OAUTH_CLIENT_SECRET
